services:
  - type: web
    name: campaign-tracker1
    env: python
    plan: free
    buildCommand: "bash .render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
